version: '3'

services:
  mariadb:
    image: mariadb:10
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user

  wordpress:
    image: wordpress
    volumes:
      - wordpress-data:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_USER: user

  wordpress-proxy:
    image: nginx
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    environment:
      UPSTREAM_URL: http://wordpress

volumes:
  mariadb-data:
  wordpress-data:
